language: ruby
rvm:
- 2.1.2
script: bundle exec rake site:deploy
branches:
  only:
  - master
  - gh-pages

env:
  global:
    secure: "jopM9XQCylMsI+T/W0KIUO+SFT80TFCfHRkQiD8uxvbCBGz5zXLT9cj+6YHnuoFsq5eSisVga3hk5SYKzIBqgJ4zrrK2AHLWCeq1h2NuPRWXMseaASKJv4t21oQOpfgdFEmFbHlzrk6ejwact2lxvHDzXqrjpLHt3vQtruIlTHQ="