language: ruby
rvm:
- 2.1.2
install:
- bundle install
script: bundle exec rake site:deploy
env:
  global:
  - secure: "VVafc1O7VVkNu8XHUf+MXSyl7LKT1npHZrfzViyBI0FbwqRSZfAyw1FAjdnwUAWGsBStDa4dACDhOszWSMj+aTpD0GJu0EFI7k/MM1CT/NjajI1TCpJ5JzzgApGi9tN4NBYTjby39oX6/uyfKOCtptX4bJTDieXdE7j4eoXxCLs="
  - secure: "J485FpH9xvc50q3cmU8bskhqef5SnXFMzFSVKXgb4F2sZa5uc9xHU3119oHtur7SyPonQ3SLsPBy5Y4UwpSMWbOPezoozcN3acsBzPxdBWzYd0FIYsZ4OpKSyuseZWGlRxOz/yMXtspimMMFB+vR8w5g2WD9a+RwFFOa8g28ux8="
  - secure: "ngezf/0vJXFclcTJ24GbHJRjurAKVJ3HwVVylxUzhEFJ24WAgo/M2Vw0aE32zkbomi9KqZ5H9HNI+b/6VyI6KJDiv+L8EserL8V+EBzduv2qyoiBbY0RFhW430EzBNQe7cOangD/6Bj53IbhFt1CVQzvY8muLyepkeVkdAZcRaM="
