language: ruby
rvm:
- 2.1.2
install:
- bundle install
script: bundle exec rake site:deploy
env:
  global:
  - secure: "VVafc1O7VVkNu8XHUf+MXSyl7LKT1npHZrfzViyBI0FbwqRSZfAyw1FAjdnwUAWGsBStDa4dACDhOszWSMj+aTpD0GJu0EFI7k/MM1CT/NjajI1TCpJ5JzzgApGi9tN4NBYTjby39oX6/uyfKOCtptX4bJTDieXdE7j4eoXxCLs="
  - secure: "J485FpH9xvc50q3cmU8bskhqef5SnXFMzFSVKXgb4F2sZa5uc9xHU3119oHtur7SyPonQ3SLsPBy5Y4UwpSMWbOPezoozcN3acsBzPxdBWzYd0FIYsZ4OpKSyuseZWGlRxOz/yMXtspimMMFB+vR8w5g2WD9a+RwFFOa8g28ux8="
  - secure: "NcpfzgVQFsQOYmM4HC+tjkd8Q/qolm/fL68Uz79N+clepTDWN8IGpfSHR2bK5mw5qbdjuCujJJGYsaH9kf2rBup1dFEIo8uj/WlNMXNxRzdPOygJi6jaOlZlT5OYdijiO8wAdlkAzb3AlmdxUB4XGzziljzg5RumO9/EhMKZ9Pk="
