# Site settings
encoding: utf-8

# Travis deploy settings
safe: false
lsi: false

relative_source: ../jekyll-travis-deploy-test
destination: ../jekyll-travis-deploy-test-pages

exclude: [vendor]
username: ercchy
repo: jekyll-travis-deploy-test


title: Peer 2 Peer University
email: admin@p2pu.org
description: "A University for the Web. Built by an open community.
LEARNING BY EVERYONE. FOR EVERYONE. ABOUT ALMOST ANYTHING. COMPLETELY FREE."
baseurl: "/p2pu-website/"
url: "http://p2pu.org"

# Build settings
markdown: kramdown
permalink: pretty









