# Site settings
encoding: utf-8

# Travis deploy settings
safe: false
lsi: false

#relative_source: ../p2pu-website
destination: ../p2pu-website/

exclude: [vendor]
username: ercchy
repo: p2pu-website


title: Peer 2 Peer University
email: admin@p2pu.org
description: "A University for the Web. Built by an open community.
LEARNING BY EVERYONE. FOR EVERYONE. ABOUT ALMOST ANYTHING. COMPLETELY FREE."
baseurl: "/p2pu-website/"
url: "http://p2pu.org"

# Build settings
markdown: kramdown
permalink: pretty









