# Site settings
encoding: utf-8

# Travis deploy settings
safe: false
lsi: false

relative_source: ../ercchy.github.io/p2pu-website
destination: ../ercchy.github.io-pages/p2pu-website-pages

exclude: [vendor]
username: ercchy
repo: p2pu-website
branch: development

title: Peer 2 Peer University
email: admin@p2pu.org
description: "A University for the Web. Built by an open community.
LEARNING BY EVERYONE. FOR EVERYONE. ABOUT ALMOST ANYTHING. COMPLETELY FREE."
baseurl: "/p2pu-website/"
url: "http://p2pu.org"

# Build settings
markdown: kramdown
permalink: pretty


navigation:
- text: Our work
  url: work/
  submenu:
  - text: P2PU Courses
    url: schools/
  - text: P2PU Schools
    url: schools/
  - text: Current and past projects
    url: projects/
  - text: Want to work with us?
    url: work_with_us
- text: About
  url: about/
  submenu:
  - text: Our people
    url: people/
  - text: Our philopsophy
    url: philosophy/
  - text: Credits
    url: credits/
- text: Publications
  url: publications/
- text: Connect with us
  url: connect/






